name: Desplegar Frontend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar dependencias
        run: |
          cd frontend
          npm ci

      - name: Compilar la app
        run: |
          cd frontend
          npm run build

      - name: Subir artefacto de la compilación
        uses: actions/upload-artifact@v4
        with:
          name: app-compilada
          path: frontend/dist

      - name: Descargar artefacto compilado
        uses: actions/download-artifact@v4
        with:
          name: app-compilada
          path: build-temp

      - name: Instalar sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Copiar archivos al home del usuario en el servidor
        env:
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          sshpass -p "$SERVER_PASSWORD" scp -P 22002 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r build-temp/* "$SERVER_USER@$SERVER_HOST:~/deploy-temp/"

      - name: Mover archivos a /var/www/html y reiniciar nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22002
          script: |
            sudo mkdir -p /var/www/html
            sudo rm -rf /var/www/html/*
            sudo cp -r ~/deploy-temp/* /var/www/html/
            sudo systemctl restart nginx
            echo "Despliegue completado"
